//! Bundled, offline template data (replaces the Python tool's `.rar` downloads).

/// (display file name, internal PropertyCode) for known properties.
pub const PROPERTIES: &[(&str, &str)] = &[
    ("Barn", "barn"),
    ("Bungalow", "bungalow"),
    ("Docks Warehouse", "dockswarehouse"),
    ("Sweatshop", "sweatshop"),
    ("Motel Room", "motelroom"),
    ("Storage Unit", "storageunit"),
    ("Hyland Manor", "manor"),
    ("Sewer Office", "seweroffice"),
];

/// (display file name, internal PropertyCode) for known businesses.
pub const BUSINESSES: &[(&str, &str)] = &[
    ("Car Wash", "carwash"),
    ("Laundromat", "laundromat"),
    ("Post Office", "postoffice"),
    ("Taco Ticklers", "tacoticklers"),
];

/// Base discoverable products (strains + hard drugs). Player-mixed products
/// are discovered automatically as they are generated.
pub const BASE_PRODUCTS: &[&str] = &[
    "ogkush",
    "sourdiesel",
    "greencrack",
    "granddaddypurple",
    "cocaine",
    "meth",
    "bennyshorseserum",
];

/// Canonical NPC ids used to add missing relationships.
pub const NPC_IDS: &[&str] = &[
    "manny_oakfield",
    "jessi_waters",
    "donna_martin",
    "jack_knight",
    "geraldine_poon",
    "keith_wagner",
    "kevin_oakley",
    "billy_kramer",
    "marco_baron",
    "stan_carney",
    "kathy_henderson",
    "beth_penn",
    "tobias_wentworth",
    "kim_delaney",
    "lisa_gardener",
    "eugene_buckley",
    "karen_kennedy",
    "trent_sherman",
    "jen_heard",
    "michael_boog",
    "dean_webster",
    "elizabeth_homley",
    "herbert_bleuball",
    "mick_lubbin",
    "genghis_barn",
    "chloe_bowers",
    "mac_cooper",
    "sam_thompson",
    "igor_romanovich_door",
    "igor_romanovich",
    "jerry_montero",
    "greg_fliggle",
    "cartelgoon5",
    "cartelgoon4",
    "cartelgoon2",
    "cartelgoon3",
    "cartelgoon1",
    "jeff_gilmore",
    "george_greene",
    "sewerking",
    "javier_perez",
    "chris_sullivan",
    "carl_bundy",
    "sherman_giles",
    "uncle_nelson",
    "oscar_holland",
    "peter_file",
    "jennifer_rivera",
    "austin_steiner",
    "hank_stevenson",
    "louis_fourier",
    "ming",
    "melissa_wood",
    "jackie_stevenson",
    "weapon_thief",
    "charles_rowland",
    "kelly_reynolds",
    "cranky_frank",
    "harold_colt",
    "kyle_cooley",
    "alison_knight",
    "walter_cussler",
    "lucy_pennington",
    "peggy_myers",
    "anna_chesterfield",
    "irene_meadows",
    "meg_cooley",
    "bruce_norton",
    "joyce_ball",
    "dan_samwell",
    "ludwig_meyer",
    "philip_wentworth",
    "pearl_moore",
    "fiona_hancock",
    "dennis_kennedy",
    "randy_caulfield",
    "ray_hoffman",
    "sewergoblin",
    "lily_turner",
    "jeremy_wilkinson",
    "doris_lubbin",
];

/// NPC ids that are dealers (used by the "recruit all dealers" action).
pub const DEALER_IDS: &[&str] = &[
    "benji_coleman",
    "molly_presley",
    "brad_crosby",
    "jane_lucero",
    "wei_long",
    "leo_rivers",
];
